n1 = eval(input("Please enter the first number: "))
n2 = eval(input("Please enter the second number: "))
print("The sum of ", n1, " and ", n2, " is ", n1+n2, ".", sep="")
print("The difference of ", n1, " and ", n2, " is ", n1-n2, ".", sep="")
print("The product of ", n1, " and ", n2, " is ", n1*n2, ".", sep="")
print("The integer division of ", n1, " and ", n2, " is ", n1//n2, ".", sep="")
print("The float division of ", n1, " and ", n2, " is ", n1/n2, ".", sep="")
print("The remainder of dividing ", n1, " by ", n2, " is ", n1%n2, ".", sep="")
